In [100]:
# This is the Week 2 Exercises based on NumpPy
import numpy as np


In [3]:
# Exercise 1: creating array and inspecting the shape
a = np.array([1, 3, 5])
b = np.array([[4, 6, 8, 10],
             [5, 10, 15, 20],
             [1, 3, 5, 7]])

In [6]:
a  #print a

array([1, 3, 5])

In [7]:
b # print b

array([[ 4,  6,  8, 10],
       [ 5, 10, 15, 20],
       [ 1,  3,  5,  7]])

In [8]:
a.shape

(3,)

In [9]:
b.shape

(3, 4)

The shape (3,4) for the array b is 3 rows and 4 columns

In [10]:
no1, no2, no3 = a
print("First no is : ", no1, " Second no is :", no2, " Third no is : ", no3)

First no is :  1  Second no is : 3  Third no is :  5


In [17]:
arr10, arr11, arr12, arr13 = b[0]
print(arr10, arr11, arr12, arr13)

4 6 8 10


In [21]:
rows, cols = b.shape

print("no of rows : ", rows, " no of cols : ", cols)

no of rows :  3  no of cols :  4


In [41]:
# Exercise 2: Indexing and slicing

M = np.array([[5, 6, 7],
              [8, 9, 10],
              [11, 12, 13],
              [25, 10, 15]])

In [43]:
#print first row
M[0]

array([5, 6, 7])

In [42]:
#print last row
M[3]

array([25, 10, 15])

In [44]:
# print Element at row 1, col 2
M[0][1]

np.int64(6)

In [47]:
# print all rows, column 0
for row in M:
    print(row[0])


5
8
11
25


In [51]:
# print Row 0, columns 1 to 2 (inclusive)
for i in M[3][1:3]:
    print(i)

10
15


In [52]:
# Exercise 3: Vectorized math
x = np.array([1.0, 2.0, 3.0])
y = np.array([10.0, 20.0, 30.0])

In [53]:
# print x + y
x + y

array([11., 22., 33.])

In [54]:
# print x**2
x **2

array([1., 4., 9.])

In [56]:
np.sum(y)

np.float64(60.0)

In [57]:
np.mean(y)

np.float64(20.0)

No, there is no need to loop...there are in built functions

In [64]:
# Exercise 4: Broadcasting
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])
bias = np.array([10.0, 20.0, 30.0])

In [62]:
A + bias

array([[11., 22., 33.],
       [14., 25., 36.]])

In [65]:
# Broadcasting applies to addition of all elements of bias array to respective rows of the given array.
#the columns number of array should be equal to no of elements in the bias array.
A.shape

(2, 3)

In [66]:
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
bias.shape

(3,)

In [68]:
# Exercise 5: Dense layer forward pas
x = np.array([2.0, 1.0, -1.0]) # (3,)
W = np.array([[1.0, 0.5],
              [0.0, -1.0],
              [2.0, 1.0]]) # (3,2)
b = np.array([0.1, -0.2]) # (2,)

In [70]:
print(x.shape)
print(W.shape)
print(b.shape)

(3,)
(3, 2)
(2,)


In [71]:
# compute out = x @ W + b
out = x @ W

In [72]:
out # output has the shape of (2,) as there are 2 columns in the array

array([ 0., -1.])

In [73]:
out = out + b

In [74]:
out

array([ 0.1, -1.2])

In [80]:
# Exercise 6: enumerate and tuple unpacking
arr = np.array([10, 20, 30, 40])

#enumerate(arr)

for idx, val in enumerate(arr):
  print(idx, val)

0 10
1 20
2 30
3 40


In [81]:
# Exercise 7: Generate synthetic linear dat
X = np.random.randn(100, 1)
noise = 0.1 * np.random.randn(100, 1)
y = 3 * X + 2 + noise

In [82]:
X.shape

(100, 1)

In [83]:
y.shape

(100, 1)

In [85]:
# print first 5 rows of X

for row in X[:5]:
  print(row)

[0.53753322]
[-0.02539196]
[1.54216874]
[1.1676257]
[0.3443427]


In [86]:
# print 5 rows of y
for row in y[:5]:
  print(row)

[3.74412329]
[1.75670058]
[6.59178807]
[5.45448819]
[2.88019775]


Each row in X represents random numbers
Each row in y repeasents 3 time value in x + twice the noise (0.1 of another random no.)

In [88]:
# Exercise 8: Estimate best-fit line (Not taught in class)
x_vals = X.reshape(-1)
x_vals

array([ 0.53753322, -0.02539196,  1.54216874,  1.1676257 ,  0.3443427 ,
       -0.15326546,  0.27537939,  0.13340107,  1.31643671, -1.067928  ,
       -0.72389077, -0.44620769, -0.41013627, -0.62799161,  0.28444326,
        0.22494211,  0.50868138,  0.72144573,  0.28289941,  0.74207636,
       -0.62854118, -0.15088328,  1.60730887, -0.39501793, -0.0287989 ,
        0.32416717, -1.63296347, -1.28125962,  0.32209765, -0.87964857,
        1.16292831, -1.12862012, -1.76451022,  1.57958467, -1.48287595,
        0.19819134,  0.68015501,  1.05401883,  1.02012996,  0.19270364,
        0.8210487 , -0.45283281, -0.03271208,  0.06609339, -0.04019439,
       -0.52653595,  0.94652734,  0.66324175,  1.43571137, -0.98365997,
        0.62095559,  1.00045123,  0.55727533, -1.2177939 , -2.41874288,
       -1.83571398, -0.02666192, -0.22249142,  0.81739828, -0.40716166,
       -0.40319745, -0.52953171, -0.29249176, -0.21841973, -1.1186323 ,
       -1.25905263,  0.81329482, -0.76576143, -1.05350479,  0.45

In [90]:
y_vals = y.reshape(-1)
y_vals

array([ 3.74412329,  1.75670058,  6.59178807,  5.45448819,  2.88019775,
        1.61604929,  2.95299886,  2.23653131,  5.9842483 , -1.03774718,
       -0.23363103,  0.84010518,  0.78038105,  0.01829952,  2.69803534,
        2.78159029,  3.58244057,  4.23614642,  2.90569274,  4.30673733,
        0.22339283,  1.85227747,  6.84181574,  0.80875076,  1.81300752,
        3.10865518, -2.84563717, -1.82047946,  3.00966584, -0.57002025,
        5.32529465, -1.41063075, -3.27239834,  6.67148183, -2.48795512,
        2.62909182,  4.0121697 ,  5.15521206,  4.97230518,  2.41185866,
        4.57436376,  0.74433352,  1.97318269,  2.13828844,  1.913434  ,
        0.62116604,  4.87110445,  3.94614302,  6.38434434, -0.76624568,
        4.00574423,  5.07103376,  3.86631597, -1.62324026, -5.27489646,
       -3.54348534,  1.92741676,  1.38213928,  4.57479952,  0.87525432,
        0.82211659,  0.63660668,  1.15574543,  1.33512836, -1.28254499,
       -1.78366128,  4.42152058, -0.28923934, -1.06838237,  3.45

In [92]:
xmean = x_vals.mean()
ymean = y_vals.mean()

In [93]:
print('xmean :' , xmean)
print('ymean :' , ymean)

xmean : -0.016377277631742487
ymean : 1.966799000198511


In [98]:
sumProd = 0.0
sqSum = 0.0

length = len(x_vals)

for i in __builtins__.range(length):
    #print(x_vals[i], y_vals[i])

    prod = (x_vals[i] - xmean) * (y_vals[i] - ymean)
    #print(prod)
    sumProd += prod

    sqX = (x_vals[i] - xmean) ** 2
    sqSum += sqX

print('sumProd :' , sumProd)
print('sqSum :' , sqSum)

w = sumProd / sqSum
print("w is : ", w)

b = ymean - w * xmean
print("b is: ", b)

for i in __builtins__.range(len(x_vals)):
    y_pred = w * x_vals[i] + b
    print("Y Preds" , y_pred)

sumProd : 257.1379635376171
sqSum : 85.75348431714343
w is :  2.9985716100658935
b is:  2.015907439955221
Y Preds 3.6277392901003935
Y Preds 1.939767833208837
Y Preds 6.640210852087785
Y Preds 5.517116718988663
Y Preds 3.048443698178672
Y Preds 1.5563299874050653
Y Preds 2.841652269024889
Y Preds 2.415920111570964
Y Preds 5.963337177181019
Y Preds -1.1863511475607997
Y Preds -0.15473087693703924
Y Preds 0.6779217279551779
Y Preds 0.7860844533170055
Y Preds 0.1328296324059135
Y Preds 2.868830911413913
Y Preds 2.6904124718432536
Y Preds 3.541224981212684
Y Preds 4.179214111000303
Y Preds 2.8642015644410685
Y Preds 4.241076543502821
Y Preds 0.13118170443316535
Y Preds 1.5634731214458222
Y Preds 6.835538199218124
Y Preds 0.8314178967132013
Y Preds 1.9295518668507594
Y Preds 2.9879459105689117
Y Preds -2.8806504580389287
Y Preds -1.8260412802688935
Y Preds 2.9817403031165957
Y Preds -0.6217817810538211
Y Preds 5.50303125604761
Y Preds -1.368340819653349
Y Preds -3.275102805469947
Y Preds 6.

In [105]:
#Exercise 9: Broadcast sanity check
B = np.random.randn(5, 4)
row_b = np.random.randn(4,)
col_b = np.random.randn(5,1)
print(B)
print(row_b)
print((B + row_b).shape)

[[ 0.29307822 -0.91539555  1.68642978  0.42793346]
 [ 0.75955152  1.35453876  0.54347147 -1.80769995]
 [-0.63460155  0.97253854  0.32210615  0.11855011]
 [-0.11373249 -0.06426643 -0.4715395   0.04707928]
 [-0.52099752 -0.60440077 -2.14007189 -1.31882597]]
[-0.14310881  0.56185409 -1.58023834 -1.19741839]
(5, 4)


In [106]:
print(col_b)
print(B + col_b)
print((B + col_b).shape)

[[ 0.92473703]
 [ 0.86871576]
 [ 0.60299045]
 [ 0.75238778]
 [-1.02292894]]
[[ 1.21781525  0.00934148  2.61116681  1.35267049]
 [ 1.62826728  2.22325451  1.41218723 -0.93898419]
 [-0.0316111   1.57552899  0.9250966   0.72154056]
 [ 0.63865529  0.68812135  0.28084828  0.79946706]
 [-1.54392646 -1.62732971 -3.16300082 -2.3417549 ]]
(5, 4)


In [108]:
baseAr = np.array([[2, 3, 4],

                   [11, 22, 33]])

rowD = np.array([3, 3, 3])
colD = np.array([[4],
                [5]])
print(baseAr + rowD)
print(baseAr + colD)

[[ 5  6  7]
 [14 25 36]]
[[ 6  7  8]
 [16 27 38]]


In [ ]:
# the shape is same as the org array
# row_b adds row-wise to all rows
# col_b adds column wise to all columns


In [109]:
# Exercise 10: Shape-mismatch debugging (challenge
u = np.array([1.0, 2.0, 3.0]) # (3,)
V = np.array([[1.0, 2.0],
              [3.0, 4.0]]) # (2,2)
print(u @ V)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [110]:
# the error is that the no of element in 1D array, should be same as # of rows in the 2D array..
# fix is to add one more row to the V array..
u = np.array([1.0, 2.0, 3.0]) # (3,)
V = np.array([[1.0, 2.0],
              [3.0, 4.0],
              [6.0, 8.0]]) # (3,2)
print(u @ V)

[25. 34.]
